version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # ✅ superset DB 자동 생성

  airflow-init:
    image: apache/airflow:2.6.3
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    entrypoint: ["airflow", "db", "init"]

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__AUTHENTICATE=True
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.www.security.AirflowSecurityManager
      - AIRFLOW_UID=50000
    volumes:
      - ./airflow:/opt/airflow:rw
    command: ["airflow", "webserver"]

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
      - airflow-webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_UID=50000
    volumes:
      - ./airflow:/opt/airflow:rw
    command: ["airflow", "scheduler"]

  superset:
    image: apache/superset:2.1.0
    container_name: superset
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp/key.json
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://airflow:airflow@postgres/superset
    volumes:
      - ~/gce_key:/app/gcp/key.json
    entrypoint: >
      bash -c "
        superset db upgrade &&
        (superset fab list-users | grep admin || \
          superset fab create-admin \
            --username admin \
            --firstname Superset \
            --lastname Admin \
            --email admin@example.com \
            --password admin) &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
volumes:
  postgres_data: