FROM apache/superset:2.1.0

USER root

# packaging 버전을 Superset과 호환되도록 고정
RUN pip install --no-cache-dir \
    "packaging<24" \
    pybigquery \
    sqlalchemy-bigquery \
    pandas-gbq

USER superset
