FROM apache/superset:1.5.2

USER root

RUN pip install --no-cache-dir \
    "packaging<21" \
    "sqlalchemy<2.0" \
    "pybigquery==0.5.0" \
    "sqlalchemy-bigquery==1.4.4" \
    "pandas-gbq==0.19.1" \
    "google-cloud-bigquery==3.6.0"

USER superset